# Generated by Django 2.1.2 on 2018-10-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('event_name', models.CharField(default='event', max_length=100)),
                ('event_description', models.CharField(blank=True, default='', max_length=100)),
                ('event_location', models.CharField(max_length=50)),
                ('event_date', models.DateTimeField(verbose_name='date of event')),
                ('event_participants', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ('creation_date',),
            },
        ),
    ]