# Generated by Django 2.1.2 on 2018-10-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('event_name', models.CharField(default='event', max_length=100)),
                ('event_description', models.CharField(blank=True, default='New event', max_length=100)),
                ('event_location', models.CharField(max_length=50)),
                ('event_participants', models.IntegerField(default=1)),
                ('event_start_time', models.DateTimeField(null=True, verbose_name='start date and time')),
                ('event_end_time', models.DateTimeField(null=True, verbose_name='start date and time')),
                ('event_price', models.DecimalField(decimal_places=2, default='0.0', max_digits=7)),
                ('event_qrenabled', models.BooleanField(default=False)),
                ('event_pic', models.ImageField(default='event_picts/None/no-img.jpg', upload_to='event_pics/')),
            ],
            options={
                'ordering': ('creation_date',),
            },
        ),
    ]
