# Generated by Django 2.1.2 on 2018-11-20 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181020_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_participants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
