# Generated by Django 2.1.2 on 2018-11-20 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20181120_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_participants',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
