# Generated by Django 2.1.2 on 2018-11-24 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_auto_20181124_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_participants',
        ),
        migrations.AddField(
            model_name='event',
            name='attending_users',
            field=models.ManyToManyField(related_name='events_attended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='event_max_capacity',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='event',
            name='favourited_users',
            field=models.ManyToManyField(related_name='events_favourited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events_hosting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='registered_users',
            field=models.ManyToManyField(related_name='events_registered', to=settings.AUTH_USER_MODEL),
        ),
    ]
