# Generated by Django 2.1.2 on 2018-11-25 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_qrenabled',
        ),
    ]
