# Generated by Django 2.1.2 on 2018-11-25 06:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_event_qrenabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('FO', 'Food'), ('NT', 'Networking'), ('PT', 'Party'), ('SP', 'Sports'), ('AC', 'Academics'), ('MU', 'Music'), ('MS', 'Miscellaneous')], default='MS', max_length=2), default=list, null=True, size=None),
        ),
    ]
