# Generated by Django 2.1.2 on 2018-11-25 08:43

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20181125_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(upload_to=events.models.path_and_rename),
        ),
    ]
