# Generated by Django 2.1.2 on 2018-11-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_event_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_pic',
        ),
    ]
