# Generated by Django 2.1.2 on 2018-11-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default="I'm a cool user for using Eventry... and I won't fail CPEN 321!", max_length=1000),
        ),
    ]
