# Generated by Django 2.1.2 on 2018-11-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expo_push_token',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
